### ISSUE TITLE
Failing tests (x-to-SBGN) for certain Java versions 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid-converters#32]
Initial observation is that two of the factoid.web -> ControllerT -> testXToSbgn tests are failing, blocking gradle builds.

I could get the tests passing with openjdk13 with some warnings, but not 8, 11, 17 and our github actions specifies 8, 11 so now any [recent builds](https://github.com/PathwayCommons/factoid-converters/actions/runs/3157302831) fail. The relevant error I've pasted below: 

```sh...
java.security.PrivilegedActionException: null.
...
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass...
```
---

Some discussions suggest adding `org.glassfish.jaxb:jaxb-runtime` which seemed to allow the tests to pass.

**Comment by IgorRodchenkov** [comment]
I can look into this. Basically, with modern JDK we need to explicitly allow some insecure code, such as reflection. 

Is factoid-converters using paxtools 5.2.1-SNAPSHOT (I recently deployed fresh snapshots to the public snapshots repo.. that might explain the error, unless nobody simply tried to build factoid-converters from sources for years ;))? Try previous version. Otherwise some more changes need to be done in the pom file, like I did in paxtools branch: release-5-2-1.


IR

**Comment by jvwong** [comment]
The gradle.build has `org.biopax.paxtools:sbgn-converter:5.2.1-SNAPSHOT`

The GitHub Actions workflow (daily?) cron paused itself about 11 months ago because of inactivity. The Docker image we use was built >1 year ago, and it seems OK as it uses openjdk-13-alpine.

**Comment by IgorRodchenkov** [comment]
Which branch shall we work in? Does that "unstable" branch still make any sense?..

**Comment by IgorRodchenkov** [comment]
We should require min java 11 (ideally 17, but some dependencies are still old) and build only with jdk18 these days.

**Comment by jvwong** [comment]
> Which branch shall we work in? Does that "unstable" branch still make any sense?..

No idea what's in those branches - @metincansiper ?

**Comment by metincansiper** [comment]
There are some changes in unstable branch that we may consider merging into master branch later. I think you can work in master branch for the time being.

**Comment by IgorRodchenkov** [comment]
I fixed in master (not sure what other branches do...)
